#!/bin/bash
set +e
FROM=$1
TO=$2

if [ $# -ne 2 ]; then
  echo "ERROR: Correct Use: ./sync-content <from> <to>"
  exit 1
fi

if [ -d "./$FROM" ]; then
  cd $FROM
  git pull --rebase
  cd ..
else
  git clone --depth=1 git@github.com:www-thoughtworks-com/$FROM.git
fi

if [ -d "./$TO" ]; then
  cd $TO
  git pull --rebase
  cd ..
else
  git clone --depth=1 git@github.com:www-thoughtworks-com/$TO.git
fi

echo Clearing metadata from $TO
rm -rf $TO/metadata

echo Clearing draft from $TO
rm -rf $TO/draft

echo Clearing public from $TO
rm -rf $TO/public

echo Copying metadata from $FROM to $TO
cp -R $FROM/metadata $TO/metadata

echo Copying draft from $FROM to $TO
cp -R $FROM/draft $TO/draft

echo Copying public from $FROM to $TO
cp -R $FROM/public $TO/public

echo Committing to Git
cd $TO
git add --all
git commit -am "$USER - Syncing content from $FROM to $TO"
git push origin master
cd ..
echo Content Synced!
